name: 'sort problem matcher'
author: 'Peter Newman'
description: 'Shows GNU sort errors as annotation (with file and code line) in GitHub Actions'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'search'
  color: 'green'
